"""add review

Revision ID: 49b35c440646
Revises: 2bdc154d9dfa
Create Date: 2024-07-05 12:36:00.352355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b35c440646'
down_revision = '2bdc154d9dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
